### ISSUE TITLE
routes.py and login.py clash

### ISSUE THREAD

**Issue by SeanLixu23445997** [seanlixu/CITS3403-RequestBoard#17]
when inputting correct login details, it wont go through the proper logic defined in the login.py file. I think its due to the fact that there are two endpoints being defined with the same endpoint name login(). to mitigate this, I suggest combining login.py and register.py 

OR

instead, remove the "post" from methods=["GET", "POST"] Inside of routes. ( i have no idea if this will work, but ill give a try)

V this is from login.py
![Screenshot 2024-05-08 at 4 37 08 pm](https://github.com/seanlixu/CITS3403-RequestBoard/assets/140785554/e2939430-c1e0-481a-8a32-1a09c0021c4f)

V this is from routes.py
![Screenshot 2024-05-08 at 4 36 54 pm](https://github.com/seanlixu/CITS3403-RequestBoard/assets/140785554/bd479806-074a-41f0-8b4d-cc5967ff50fe)

**Comment by SeanLixu23445997** [comment]
ill clean up the code accordingly

**Comment by paulmmaingi** [comment]
I am in the process of refactoring the backend code in order to modularise the authentication and use handlers for logging in and out.
