### ISSUE TITLE
$FLASK_APP name not being set

### ISSUE THREAD

**Issue by normit581** [seanlixu/CITS3403-RequestBoard#31]
![image](https://github.com/seanlixu/CITS3403-RequestBoard/assets/139199443/4d80ca38-b828-453f-a95f-ab6c7f03e690)

I am getting this error when trying to run flask run --debug in venv. When I set FLASK_APP=task_link.py it then works, anyone know what might be causing this?

Could we add into config a line where it sets this automatically as a fix?

@seanlixu @paulmaingi

**Comment by paulmmaingi** [comment]
Yeah if u have `.env` file with environment variable `FLASK_APP=task_link`, it will work.
